spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SOCCER;encrypt=true;trustServerCertificate=true
    username: sa
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
